#!/bin/bash

if [ "$1" == "start" ]; then
    echo "Starting up java ..."
    export JOBBOARD_BASE_PATH=/jobs
    java -cp "lib/*:src/:resources/" clojure.main src/jobboard/core.clj &
elif [ "$1" == "stop" ]; then
    kill `pgrep -f "java -cp lib/\*:src/:resources/ clojure.main src/jobboard/core.clj"`
fi

